name = "Cargo Contributor Mentorship Office Hours"
description = """Cargo Contributor Mentorship Office Hours"""

[meta]
includes = [ "../_timezones.toml" ]

[[events]]
uid = "1704825224734"
title = "Cargo Contributor Mentorship Office Hours"
description = """Cargo Contributor Mentorship Office Hours
Propose topics at https://rust-lang.zulipchat.com/#narrow/stream/246057-t-cargo/topic/Contributor.20mentorship.20office.20hours
"""
location = "https://meet.jit.si/CargoOfficeHours"
created_on = "2024-01-09T18:34:47.02Z"
last_modified_on = "2024-12-18T16:06:21.48Z"
start = { date = "2024-01-10T10:00:00.00", timezone = "America/New_York" }
end = { date = "2024-01-10T11:00:00.00", timezone = "America/New_York" }
status = "confirmed"
organizer = { name = "t-cargo", email = "cargo@rust-lang.org" }
recurrence_rules = [
    { frequency = "weekly", by_day = [{ day = "wednesday" }], by_hour = [10] },
    { frequency = "weekly", by_day = [{ day = "thursday" }], by_hour = [16] }
]
exceptions = [
    "2024-12-25T15:00:00.00Z",
    "2024-12-26T21:00:00.00Z",
    "2025-01-01T15:00:00.00Z",
    "2025-01-02T21:00:00.00Z",
]
