name = "Cargo Resolver and PubGrub Office Hours"
description = """Office hours to discuss dependency resolution in general, Cargo's Resolvers, or the PubGrub project"""

[meta]
includes = [ "../_timezones.toml" ]

[[events]]
uid = "1704827269860"
title = "Cargo Resolver and PubGrub Office Hours"
description = """Office hours to discuss dependency resolution in general, Cargo's Resolvers, or the PubGrub project
Propose topics at https://rust-lang.zulipchat.com/#narrow/stream/260232-t-cargo.2FPubGrub/topic/Office.20hours
"""
location = "https://meet.jit.si/CargoOfficeHours"
created_on = "2024-01-09T19:08:15.06Z"
last_modified_on = "2024-06-07T16:48:03.72Z"
start = { date = "2024-01-17T13:00:00.00", timezone = "America/New_York" }
end = { date = "2024-01-17T15:00:00.00", timezone = "America/New_York" }
status = "confirmed"
organizer = { name = "T-cargo", email = "cargo@rust-lang.org" }
recurrence_rules = [ { frequency = "weekly" } ]
exceptions = [ "2024-03-27T17:00:00.00Z", "2024-04-03T17:00:00.00Z", "2024-04-17T17:00:00.00Z", "2024-04-24T17:00:00.00Z", "2024-06-12T17:00:00.00Z" ]
