name = "Cargo Team"
description = "Meetings for the Cargo team"

[meta]
includes = [ "../_timezones.toml" ]

[[events]]
uid = "1704823793158"
title = "Cargo Team Weekly Meeting"
description = """The Cargo team's weekly meeting.
Notes: https://hackmd.io/_K2Le1ZbQEykvhIQvQI7Hw"""
location = "https://meet.jit.si/CargoTeamMeeting"
created_on = "2024-01-09T18:14:00.94Z"
last_modified_on = "2024-01-17T16:48:03.72Z"
start = { date = "2024-01-16T10:00:00.00", timezone = "America/New_York" }
end = { date = "2024-01-16T11:00:00.00", timezone = "America/New_York" }
status = "confirmed"
organizer = { name = "T-cargo", email = "cargo@rust-lang.org" }
recurrence_rules = [ { frequency = "weekly" } ]