name = "Cargo Team"
description = "Meetings for the Cargo team"

[meta]
includes = [ "_timezones.toml" ]

[[events]]
uid = "1704823793158"
title = "Cargo Team Weekly Meeting"
description = """The Cargo team's weekly meeting.
Notes: https://hackmd.io/_K2Le1ZbQEykvhIQvQI7Hw"""
location = "https://meet.jit.si/CargoTeamMeeting"
created_on = "2024-01-09T18:14:00.94Z"
last_modified_on = "2024-01-09T18:14:00.94Z"
start = { date = "2024-01-16T10:00:00.00", timezone = "America/New_York" }
end = { date = "2024-01-16T11:00:00.00", timezone = "America/New_York" }
status = "confirmed"
organizer = { name = "T-cargo", email = "cargo@rust-lang.org" }
recurrence_rules = [ { frequency = "weekly" } ]

[[events]]
uid = "1704825224734"
title = "Cargo Contributor Mentorship Office Hours"
description = """Cargo Contributor Mentorship Office Hours"""
location = "https://meet.jit.si/CargoOfficeHours"
created_on = "2024-01-09T18:34:47.02Z"
last_modified_on = "2024-01-11T16:20:35.83Z"
start = { date = "2024-01-10T10:00:00.00", timezone = "America/New_York" }
end = { date = "2024-01-10T11:00:00.00", timezone = "America/New_York" }
status = "confirmed"
organizer = { name = "t-cargo", email = "cargo@rust-lang.org" }
recurrence_rules = [
    { frequency = "weekly", by_day = [{ day = "wednesday" }], by_hour = [10] },
    { frequency = "weekly", by_day = [{ day = "thursday" }], by_hour = [16] }
]

[[events]]
uid = "1704827269860"
title = "PubGrub Office Hours"
description = """Office hours for the PubGrub project"""
location = "https://meet.jit.si/CargoOfficeHours"
created_on = "2024-01-09T19:08:15.06Z"
last_modified_on = "2024-01-09T19:08:15.06Z"
start = { date = "2024-01-17T13:00:00.00", timezone = "America/New_York" }
end = { date = "2024-01-17T14:00:00.00", timezone = "America/New_York" }
status = "confirmed"
organizer = { name = "T-cargo", email = "cargo@rust-lang.org" }
recurrence_rules = [ { frequency = "weekly" } ]
