name = "Content team"
description = "Meetings for the Content team"

[meta]
includes = [ "_timezones.toml" ]

[[events]]
uid = "10a002e5ce160f94e5bb286ebc392b9b31f7cf67"
title = "Content Team Meeting"
description = "Review, planning, and catch-up with the Content team"
location = "https://meet.google.com/hen-fyep-krt"
last_modified_on = "2025-09-11T12:00:00.00Z"
start = { date = "2025-09-11T11:00:00.00", timezone = "America/New_York" }
end = { date = "2025-09-11T12:00:00.00", timezone = "America/New_York" }
status = "confirmed"
transparency = "opaque"
organizer = { name = "t-content", email = "content@rust-lang.org" }
recurrence_rules = [ { frequency = "weekly", interval = 2 } ]
