name = "Rust Leadership Council"
description = "Meetings of the Rust Leadership Council"

[meta]
includes = [ "_timezones.toml" ]

[[events]]
uid = "1705586649144"
title = "Leadership Council Meeting"
description = "Regular meeting of the Rust leadership council"
location = "See meeting's thread in https://rust-lang.zulipchat.com/#narrow/stream/392734-council"
last_modified_on = "2024-01-18T14:04:00.00Z"
start = { date = "2024-01-19T11:30:00.00", timezone = "America/New_York" }
end = { date = "2024-01-19T12:30:00.00", timezone = "America/New_York" }
status = "confirmed"
organizer = { name = "Rust Leadership Council", email = "council@rust-lang.org" }
recurrence_rules = [ { frequency = "weekly", interval = 2 } ]

[[events]]
uid = "abeb70d949c5d5bfa94372a89a8a0574a13980d6"
title = "Leadership Council Update blog post"
description = "Write and publish the regular Leadership Council Update blog post on the Inside Rust blog"
location = "Inside Rust blog"
last_modified_on = "2026-07-23T08:00:00.00Z"
start = "2026-09-01T13:00:00.00Z"
end = "2026-09-01T14:00:00.00Z"
status = "confirmed"
organizer = { name = "Rust Leadership Council", email = "council@rust-lang.org" }
recurrence_rules = [ { frequency = "monthly", interval = 3 } ]

[[events]]
uid = "d5f4fa824fa28d029d2c999ddf8fafa50c993b0e"
title = "Leadership Council Performance survey"
description = "Write and publish the regular Leadership Council Performance survey amongst Rust Project members. Once the survey is finished, analyze the results and write a blog post."
location = "Rust Project Zulip"
last_modified_on = "2026-07-23T08:00:00.00Z"
start = "2027-06-01T13:00:00.00Z"
end = "2027-06-01T14:00:00.00Z"
status = "confirmed"
organizer = { name = "Rust Leadership Council", email = "council@rust-lang.org" }
recurrence_rules = [ { frequency = "yearly", interval = 1 } ]
