name = "Rust Releases Calendar"
description = "New releases of Rust"

[[events]]
uid = "1706194117478"
title = "New Rust Release"
last_modified_on = "2024-01-25T00:00:00.00Z"
start = "2024-02-08"
organizer = { name = "t-infra", email = "infra@rust-lang.org" }
recurrence_rules = [ { frequency = "weekly", interval = 6 } ]
