name = "Rust Releases"
description = "New releases of Rust"

[[events]]
uid = "1706194117478"
title = "New Rust Release"
last_modified_on = "2024-01-25T00:00:00.00Z"
start = "2024-02-08"
organizer = { name = "t-infra", email = "infra@rust-lang.org" }
recurrence_rules = [ { frequency = "weekly", interval = 6 } ]

# Deleted event, this belongs in a separate calendar file (release-team.toml).
[[events]]
uid = "42985c1ccc9931952a2eecb21f96ec06ecea5492"
title = "Release Team Meeting"
last_modified_on = "2025-02-10T00:00:00.00Z"
organizer = { name = "t-release", email = "release@rust-lang.org" }
description = "Weekly team meeting"
location = "#t-release on Zulip (https://rust-lang.zulipchat.com/#narrow/channel/241545-t-release)"
start = { date = "2025-01-31T12:30:00.00", timezone = "America/New_York" }
end = { date = "2025-01-31T13:00:00.00", timezone = "America/New_York" }
status = "confirmed"
recurrence_rules = [ { frequency = "weekly", until = "2025-02-19T13:50:00.00Z" } ]
