name = "Rustdoc Team"
description = "Meetings for the Rustdoc team"

[[events]]
uid = "1704823643569"
title = "Rustdoc meeting"
description = "Monthly team meeting of the Rustdoc team"
location = "#t-rustdoc/meetings on Zulip (https://rust-lang.zulipchat.com/#narrow/stream/t-rustdoc.2Fmeetings)"
last_modified_on = "2024-04-09T04:15:00.00Z"
start = { date = "2024-05-13T21:00:00.00", timezone = "Europe/Paris" }
end = { date = "2024-05-13T22:00:00.00", timezone = "Europe/Paris" }
status = "confirmed"
organizer = { name = "rustdoc", email = "rustdoc@rust-lang.org" }
recurrence_rules = [ { frequency = "monthly", by_day = [ { day = "monday", num = 2 } ] } ]
