name = "Rust Types Team"
description = "Meetings for the types team and its working groups"

[meta]
includes = [ "_timezones.toml" ]

[[events]]
uid = "1704470313292"
title = "Types Team Meeting"
description = "Weekly team meeting of the types team"
location = "#t-types/meetings on Zulip (https://rust-lang.zulipchat.com/#narrow/stream/326132-t-types.2Fmeetings)"
last_modified_on = "2024-12-17T10:00:00.00Z"
start = { date = "2024-01-08T10:00:00.00", timezone = "America/New_York" }
end = { date = "2024-01-08T11:00:00.00", timezone = "America/New_York" }
status = "confirmed"
organizer = { name = "t-types", email = "types@rust-lang.org" }
recurrence_rules = [ { frequency = "weekly", until = "2024-11-13T00:00:00.00Z" } ]

[[events]]
uid = "1704471680390"
title = "Types Team: ITE (Impl Trait Everywhere) Triage"
description = "Regular triage of the implementation of impl Trait-related features"
location = "https://meet.jit.si/impl-trait-everywhere"
last_modified_on = "2025-02-07T10:00:00.00Z"
start = { date = "2024-01-11T16:00:00.00", timezone = "America/New_York" }
end = { date = "2024-01-11T16:30:00.00", timezone = "America/New_York" }
status = "confirmed"
organizer = { name = "t-types", email = "types@rust-lang.org" }
recurrence_rules = [ { frequency = "weekly", until = "2024-11-13T00:00:00.00Z" } ]

[[events]]
uid = "5183091736401"
title = "Types Team High Bandwidth Discussions"
description = "Regular meeting discussing items from the Types Team roadmap"
location = "https://meet.jit.si/curry-howard-ftw"
last_modified_on = "2025-02-07T10:00:00.00Z"
start = { date = "2024-04-30T10:30:00.00", timezone = "America/New_York" }
end = { date = "2024-04-30T12:00:00.00", timezone = "America/New_York" }
status = "confirmed"
organizer = { name = "t-types", email = "types@rust-lang.org" }
recurrence_rules = [ { frequency = "weekly", until = "2024-11-13T00:00:00.00Z" } ]

[[events]]
uid = "09038f9ca2b7d003a12249d8d20a8b5971d4bf71"
title = "Types Team Office Hours (Video call)"
description = "Weekly team office hours (video call)"
location = "https://meet.jit.si/curry-howard-ftw"
last_modified_on = "2025-05-26T10:00:00.00Z"
start = { date = "2025-06-03T10:30:00.00", timezone = "America/New_York" }
end = { date = "2025-06-03T12:00:00.00", timezone = "America/New_York" }
status = "confirmed"
organizer = { name = "t-types", email = "types@rust-lang.org" }
recurrence_rules = [ { frequency = "monthly", by_day = [ { day = "tuesday", num = 1 } ] } ]

[[events]]
uid = "1de33be55f71f9eebc5ef0d8ea7132c1e3561cb9"
title = "Types Team Office Hours (Zulip chat)"
description = "Weekly team office hours (zulip chat)"
location = "https://rust-lang.zulipchat.com/#narrow/channel/326132-t-types.2Fmeetings"
last_modified_on = "2025-05-26T10:00:00.00Z"
start = { date = "2025-05-27T10:30:00.00", timezone = "America/New_York" }
end = { date = "2025-05-27T12:00:00.00", timezone = "America/New_York" }
status = "confirmed"
organizer = { name = "t-types", email = "types@rust-lang.org" }
recurrence_rules = [ { frequency = "monthly", by_day = [ { day = "tuesday", num = 2 }, { day = "tuesday", num = 3 }, { day = "tuesday", num = 4 }, { day = "tuesday", num = 5 } ] } ]
