name = "Rust Types Team"
description = "Meetings for the types team and its working groups"

[[events]]
uid = "1704470313292"
title = "Types Team Meeting"
description = "Weekly team meeting of the types team"
location = "#t-types/meetings on Zulip (https://rust-lang.zulipchat.com/#narrow/stream/326132-t-types.2Fmeetings)"
last_modified_on = "2024-01-05T15:49:00.00Z"
start = "2024-01-08T15:00:00.00Z"
end = "2024-01-08T16:00:00.00Z"
status = "confirmed"
organizer = { name = "t-types", email = "types@rust-lang.org" }
recurrence_rules = [ { frequency = "weekly" } ]

[[events]]
uid = "1704471680390"
title = "Types Team: ITE (Impl Trait Everywhere) Triage"
description = "Regular triage of the implementation of impl Trait-related features"
location = "Jitsi (https://meet.jit.si/impl-trait-everywhere)"
last_modified_on = "2024-01-05T16:22:00.00Z"
start = "2024-01-11T21:00:00.00Z"
end = "2024-01-11T21:30:00.00Z"
status = "confirmed"
organizer = { name = "t-types", email = "types@rust-lang.org" }
recurrence_rules = [ { frequency = "weekly" } ]

[[events]]
uid = "1704471804390"
title = "Types Team: Rotating Solver/Formality/Polonius Deep Dive"
description = "Rotating deep dive into a types team project (https://hackmd.io/jjc-a_V4RWOYFTVpVeVsCA)"
location = "Jitsi (https://meet.jit.si/p-equals-np)"
last_modified_on = "2024-01-05T16:24:00.00Z"
start = "2024-01-08T16:00:00.00Z"
end = "2024-01-08T17:30:00.00Z"
status = "confirmed"
organizer = { name = "t-types", email = "types@rust-lang.org" }
recurrence_rules = [ { frequency = "weekly" } ]
