name = "Debugging Working Group"
description = "Providing users with a great experience when debugging Rust code"

[[events]]
uid = "1704470530167"
title = "wg-debugging Triage Meeting"
description = "Triage of outstanding debugging issues"
location = "#t-compiler/wg-debugging on Zulip (https://rust-lang.zulipchat.com/#narrow/stream/317568-t-compiler.2Fwg-debugging)"
last_modified_on = "2024-01-05T16:01:00.00Z"
start = "2024-01-15T15:00:00.00Z"
end = "2024-01-15T16:00:00.00Z"
status = "confirmed"
organizer = { name = "wg-debugging", email = "compiler@rust-lang.org" }
recurrence_rules = [ { frequency = "weekly", until = "2024-12-04T12:00:00.00Z" } ]