name = "Performance Working Group"
description = "Meetings for the compiler performance working group"

[[events]]
uid = "1704470086455"
title = "Performance Triage Deadline"
description = "Approximate time when performance triage should happen by"
location = "#t-compiler/performance on Zulip (https://rust-lang.zulipchat.com/#narrow/stream/247081-t-compiler.2Fperformance)"
last_modified_on = "2024-01-05T15:56:00.00Z"
start = "2024-01-09T16:00:00.00Z"
end = "2024-01-09T17:00:00.00Z"
status = "confirmed"
organizer = { name = "wg-performance", email = "compiler@rust-lang.org" }
recurrence_rules = [ { frequency = "weekly" } ]

[[events]]
uid = "1704731526331"
title = "simulacrum: performance triage"
description = """simulacrum's turn to do performance triage

1. Open a date-tagged topic in zulip t-compiler/performance
2. Do the triage (see https://github.com/rust-lang/rustc-perf/tree/master/triage#readme)
3. Post PRs to rust-lang/rustc-perf and rust-lang/this-week-in-rust"""
location = "#t-compiler/performance on Zulip (https://rust-lang.zulipchat.com/#narrow/stream/247081-t-compiler.2Fperformance)"
last_modified_on = "2024-01-08T16:36:00.00Z"
start = "2024-01-08"
status = "confirmed"
organizer = { name = "wg-performance", email = "compiler@rust-lang.org" }
recurrence_rules = [ { frequency = "weekly", interval = 4 } ]

[[events]]
uid = "1704733471492"
title = "pnkfelix: performance triage"
description = """pnkfelix's turn to do performance triage

1. Open a date-tagged topic in zulip t-compiler/performance
2. Do the triage (see https://github.com/rust-lang/rustc-perf/tree/master/triage#readme)
3. Post PRs to rust-lang/rustc-perf and rust-lang/this-week-in-rust"""
location = "#t-compiler/performance on Zulip (https://rust-lang.zulipchat.com/#narrow/stream/247081-t-compiler.2Fperformance)"
last_modified_on = "2024-01-08T17:04:00.00Z"
start = "2024-01-15"
status = "confirmed"
organizer = { name = "wg-performance", email = "compiler@rust-lang.org" }
recurrence_rules = [ { frequency = "weekly", interval = 4 } ]

[[events]]
uid = "1704796350522"
title = "kobzol: performance triage"
description = """kobzol's turn to do performance triage

1. Open a date-tagged topic in zulip t-compiler/performance
2. Do the triage (see https://github.com/rust-lang/rustc-perf/tree/master/triage#readme)
3. Post PRs to rust-lang/rustc-perf and rust-lang/this-week-in-rust"""
location = "#t-compiler/performance on Zulip (https://rust-lang.zulipchat.com/#narrow/stream/247081-t-compiler.2Fperformance)"
last_modified_on = "2024-01-09T10:32:00.00Z"
start = "2024-01-22"
status = "confirmed"
organizer = { name = "wg-performance", email = "compiler@rust-lang.org" }
recurrence_rules = [ { frequency = "weekly", interval = 4 } ]

[[events]]
uid = "1704733549327"
title = "rylev: performance triage"
description = """rylev's turn to do performance triage

1. Open a date-tagged topic in zulip t-compiler/performance
2. Do the triage (see https://github.com/rust-lang/rustc-perf/tree/master/triage#readme)
3. Post PRs to rust-lang/rustc-perf and rust-lang/this-week-in-rust"""
location = "#t-compiler/performance on Zulip (https://rust-lang.zulipchat.com/#narrow/stream/247081-t-compiler.2Fperformance)"
last_modified_on = "2024-01-08T17:05:00.00Z"
start = "2024-01-29"
status = "confirmed"
organizer = { name = "wg-performance", email = "compiler@rust-lang.org" }
recurrence_rules = [ { frequency = "weekly", interval = 4 } ]
