name: check calendars

on:
  pull_request:

jobs:
  generate:
    name: generate
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.1.1
      - name: Generate calendars
        uses: rust-lang/calendar-generation@main
